export enum BookingType {
  FLIGHT = 'FLIGHT',
  ACCOMMODATION = 'ACCOMMODATION',
  CAR_RENTAL = 'CAR_RENTAL',
  RESTAURANT = 'RESTAURANT',
  ACTIVITY = 'ACTIVITY',
  TRANSPORT = 'TRANSPORT'
}

export enum PendingBookingStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  REJECTED = 'REJECTED'
}

export enum MealType {
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER'
}

export enum DaySlotType {
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER',
  ACCOMMODATION = 'ACCOMMODATION'
}
